name: $(BuildID)

trigger:
- '*'

pool:
  name: Hosted VS2017

jobs:
- job: DscBuild
  strategy:
    parallel: 4
  pool:
    name: Default
  workspace:
    clean: all
  steps:
    - powershell: '.\Build.ps1 -ResolveDependency'
      workingDirectory: DSC
      displayName: 'Execute build.ps1'

    - task: PublishTestResults@2
      displayName: 'Publish Integration Test Results'
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: '**/IntegrationTestResults.xml'
        failTaskOnFailedTests: true

    - task: PublishBuildArtifacts@1
      displayName: MOF
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\MOF'
        ArtifactName: MOF

    - task: PublishBuildArtifacts@1
      displayName: 'Meta MOF'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\MetaMOF'
        ArtifactName: 'Meta MOF'

    - task: PublishBuildArtifacts@1
      displayName: RSOP
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\RSOP'
        ArtifactName: RSOP

    - task: PublishBuildArtifacts@1
      displayName: 'Compressed Modules'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\DSC\BuildOutput\CompressedModules'
        ArtifactName: 'Compressed Modules'

    - task: PublishTestResults@2
      displayName: 'Publish Build Acceptance Test Results'
      inputs:
        testResultsFormat: NUnit
        testResultsFiles: '**/BuildAcceptanceTestResults.xml'
        failTaskOnFailedTests: true
