Configurations:
  - DscLcmController
  - DscLcmMaintenanceWindows
  - DscTagging
  - DscDiagnostic

DscTagging:
  Version: 0.3.0

DscLcmMaintenanceWindows:
  MaintenanceWindow:
    - Name: Always
      StartTime: 00:00:00
      Timespan: 24:00:00
    #- Name: FirstWednesdayNight
    #  DayOfWeek: Wednesday
    #  StartTime: 00:30:00
    #  Timespan: 02:00:00
    #  On: 1st
    #- Name: SundayAllDay
    #  DayOfWeek: Sunday
    #  StartTime: 00:00:00
    #  Timespan: 24:00:00

DscLcmController:
  MaintenanceWindowMode: AutoCorrect # or Monitor. In Monitor mode the LCM won't do changes in maintenance window.
  MonitorInterval: 00:05:00          #  
  AutoCorrectInterval: 00:10:00      #
  AutoCorrectIntervalOverride: false #   THESE VALUES ARE VERY LOW FOR EASY TESTING AND DEMONSTRATIONS
  RefreshInterval: 00:20:00          #
  RefreshIntervalOverride: false     #   PLEASE INCREASE THE VALUES TO PREVENT OVERLOADING THE PULL SERVER
  ControllerInterval: 00:01:00       #   AS WELL AS THE NODES. ALSO THE SQL DATABASE GROWS PRETTY FAST IF A
  MaintenanceWindowOverride: false   #   REPORT IS SENT EVERY 5 MINUTES.
  WriteTranscripts: true             #

LcmConfig:
  Settings:
    RefreshMode: Pull
    RefreshFrequencyMins: 30
    RebootNodeIfNeeded: true
    ActionAfterReboot: ContinueConfiguration
    AllowModuleOverwrite: true
    #CertificateID: ...
    ConfigurationMode: ApplyAndMonitor
    ConfigurationModeFrequencyMins: 30
  ConfigurationRepositoryWeb:
    Server:
      ServerURL: https://dscpull01.contoso.com:8080/PSDSCPullServer.svc
      RegistrationKey: ec717ee9-b343-49ee-98a2-26e53939eecf
  ReportServerWeb:
      ServerURL: https://dscpull01.contoso.com:8080/PSDSCPullServer.svc
      RegistrationKey: ec717ee9-b343-49ee-98a2-26e53939eecf
